[package]
name = "fonttest"
version = "0.1.0"
edition = "2024"
rust-version = "1.95"
publish = false

[lib]
name = "fonttest_web"
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0"
bymsdfgen-core = { git = "https://github.com/dsvensson/bymsdfgen" }
bymsdfgen-io = { git = "https://github.com/dsvensson/bymsdfgen" }
bytemuck = { version = "1.23", features = ["derive"] }
clap = { version = "4.5", features = ["derive"] }
glam = "0.30"
harfrust = "0.13"
log = "0.4"
read-fonts = "0.43"
sha2 = "0.10"
unicode-linebreak = "0.1"
wgpu = "30"
winit = "0.30"
wuff = { version = "0.2.8", default-features = false, features = ["brotli"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
directories = "6.0"
env_logger = "0.11"
fontdb = "0.24"
pollster = "0.4"
ureq = "3.4"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1"
console_log = "1.0"
gloo-net = { version = "0.7", default-features = false, features = ["http"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Location", "UrlSearchParams", "Window"] }

[dev-dependencies]
naga = { version = "30", features = ["wgsl-in"] }

[profile.release]
lto = "thin"
codegen-units = 1
